#!/bin/sh

if grep "^fixup!" $1; then
  exit 0
fi

exitcode=0

tput setaf 1

length=$(head -n 1 $1 | wc -m | xargs echo)

if [ "$length" -gt "50" ]; then
  exitcode=1
  echo "${red}First line of commit message was $length/50 characters long"
fi

tput sgr0

exit $exitcode
